### ISSUE TITLE
change in format of response

### ISSUE THREAD

**Issue by drdhaval2785** [avinashvarna/avinashvarna.github.io#3]
Current one. See https://github.com/drdhaval2785/prakriya/issues/19
```
     {
        "form": "भू",
        "sutra": "भूवादयो धातवः",
        "sutra_num": "१।३।१"
      },
      {
        "form": "भू",
        "sutra": "सनाद्यन्ता धातवः",
        "sutra_num": "३।१।३२"
      },
```

The UI needs to be updated to have the change from list to dict.

**Comment by avinashvarna** [comment]
UI updated. Btw, if you want to serve the UI from the prakriya repo itself via a docs folder (https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) then let me know. I will send a PR to that repo.
