### ISSUE TITLE
Behaviour when no result is given by API

### ISSUE THREAD

**Issue by drdhaval2785** [avinashvarna/avinashvarna.github.io#5]
https://github.com/drdhaval2785/prakriya/issues/38

Give No Result or something like that when the API doesn't give required information or errors out.

**Comment by avinashvarna** [comment]
I will add some error-handling, but the behavior of the API changed as well. Previously, it would return a proper error message if the form was not found. Now there is just a 500 Internal server error.

**Comment by drdhaval2785** [comment]
I agree that the API has changed a bit of its error handling. Earlier API
had separate code base, but as the python-prakriya package got a bit
stable, I decided to remove the API code and use package to retrieve data,
so as to keep single code base to maintain. But yes, the error handling of
package needs better responses. Currently it breaks with stacktrace.
Therefore it gives 500 error.

**Comment by avinashvarna** [comment]
Fixed. Please check and close.
